name: Auto Commit

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create file
      run: |
        echo "This is a dummy file." > dummy.txt
    
    - name: Commit changes
      run: |
        git config --local user.email "21mb358@esisalama.org"
        git config --local user.name "lumiere-MULAGWA"
        git add .
        git commit -m "Auto commit every 10 minutes"
        git push
